# Generated by Django 3.2 on 2022-02-02 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='access',
            field=models.CharField(default='Access', max_length=254),
        ),
        migrations.AddField(
            model_name='service',
            name='original_music',
            field=models.CharField(default='Original Music', max_length=254),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(max_length=400),
        ),
    ]
