# Generated by Django 3.2 on 2022-02-22 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20220202_1104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='frequency',
        ),
    ]
