# Generated by Django 3.2 on 2022-02-22 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_remove_service_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='subscription',
            field=models.CharField(default='Subscription', max_length=254),
        ),
    ]
