# Generated by Django 3.2 on 2022-04-18 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_library', '0003_auto_20220418_1545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='description',
        ),
        migrations.RemoveField(
            model_name='music',
            name='iframe',
        ),
    ]
