# Generated by Django 3.2 on 2022-04-18 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_library', '0006_music_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='description',
            field=models.TextField(max_length=400),
        ),
    ]
