# Generated by Django 3.2 on 2022-04-18 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_library', '0007_alter_music_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Music',
        ),
    ]
