# Generated by Django 3.2 on 2022-04-19 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_library', '0010_rename_image_url_music_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='image_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
