# Generated by Django 3.2 on 2022-04-19 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_library', '0011_music_image_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='music',
            options={'verbose_name_plural': 'Music'},
        ),
    ]
